class Solution {
private:
    /*
        Parse the expression starting at index i.

        Returns all possible strings generated by this expression.
    */
    unordered_set<string> dfs(const string& expression, int& i) {
        unordered_set<string> answer;

        /*
            current represents the result of the current
            concatenation chain.

            Example:

                {a,b}c

            After processing {a,b}:
                current = {a, b}

            After processing c:
                current = {ac, bc}
        */
        unordered_set<string> current;

        while (i < expression.size() && expression[i] != '}') {

            /*
                A comma means UNION.

                Example:

                    {a,b}

                Move the current branch into answer and
                start a new branch.
            */
            if (expression[i] == ',') {

                for (const string& word : current) {
                    answer.insert(word);
                }

                current.clear();
                ++i;
            }

            /*
                Parse the next atomic expression.

                It can be:
                1. A normal word
                2. A nested {...} expression
            */
            unordered_set<string> next;

            if (expression[i] == '{') {
                // Skip '{'
                ++i;

                next = dfs(expression, i);

                // Skip '}'
                ++i;
            } else {
                string word;

                while (i < expression.size() && isalpha(expression[i])) {
                    word.push_back(expression[i]);
                    ++i;
                }

                next.insert(word);
            }

            /*
                Concatenation:

                    current × next

                If current is empty, this is the first
                component, so simply initialize it.

                Otherwise, generate every possible combination.
            */
            if (current.empty()) {
                current = move(next);
            } else {
                unordered_set<string> combined;

                for (const string& left : current) {
                    for (const string& right : next) {
                        combined.insert(left + right);
                    }
                }

                current = move(combined);
            }
        }

        /*
            The final concatenation branch also belongs to
            the union.
        */
        for (const string& word : current) {
            answer.insert(word);
        }

        return answer;
    }

public:
    // Time: O(n*M) Space: O(n*M)
    vector<string> braceExpansionII(string expression) {
        int index = 0;

        unordered_set<string> generated = dfs(expression, index);

        vector<string> answer(generated.begin(), generated.end());

        sort(answer.begin(), answer.end());

        return answer;
    }
};
